apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: kafdrop
    app.kubernetes.io/name: kafdrop
  name: kafdrop
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: kafdrop
      app.kubernetes.io/name: kafdrop
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kafdrop
        app.kubernetes.io/name: kafdrop
    spec:
      containers:
      - name: kafdrop
        image: obsidiandynamics/kafdrop:4.2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        env:
        - name: KAFKA_BROKERCONNECT
          value: cluster-kafka-bootstrap:9092
        - name: KAFKA_PROPERTIES_FILE
          value: /etc/kafdrop/kafka.properties
        - name: JVM_OPTS
          value: -Xms32M -Xmx64M
        - name: JMX_PORT
          value: "8686"
        - name: KAFKA_TRUSTSTORE_FILE
          value: kafka.truststore.jks
        - name: KAFKA_KEYSTORE_FILE
          value: kafka.keystore.jks
        - name: SERVER_PORT
          value: "9000"
        - name: CMD_ARGS
          # value: --schemaregistry.connect=http://apicurioregistry-app-service:8080/apis/ccompat/v7
          value: --schemaregistry.connect=http://schema-registry:8081 --schemaregistry.auth=kafdrop:supers1creto
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 1m
            memory: 128Mi
        volumeMounts:
        - name: kafka-config
          mountPath: /etc/kafdrop
      volumes:
      - name: kafka-config
        configMap:
          name: kafka-config
          defaultMode: 0644




