apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka
resources:
  - kafka-secrets.yaml
  - kafka-user.yaml
  - kafka-topic.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: schema-registry-jaas
    files:
      - registry-jaas.conf=registry-jaas.conf